#!/usr/bin/env python
import version
import os

# Godot platform specifics

Import("env")

files = [
    "godot_switch.cpp",
    "joypad_switch.cpp",
    "touch_screen_switch.cpp",
    "audio_driver_switch.cpp",
    "os_switch.cpp",
    "gl_manager_switch.cpp",
    "display_server_switch.cpp",
    "switch_singleton.cpp",
]

program = env.add_program("#bin/godot", files)